TechJobhunt/Models/ErrorViewModel.cs
namespace TechJobhunt.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TechJobhunt/Areas/BatchJob/Controllers/JobListenerController.cs
using Microsoft.AspNetCore.Mvc;
using TechJobhunt.TechRepository.ILBusiness;

namespace TechJobhunt.Areas.BatchJob.Controllers
{
    [Area("BatchJob")]
    public class JobListenerController : Controller
    {
        private readonly ILJobFilter _iJobfilter;
        public JobListenerController(ILJobFilter lJobFilter)
        {
            _iJobfilter = lJobFilter;
        }
        [Route("/techpanel")]
        public IActionResult TechPanel(string tag, string type)
        {
            ViewBag.Description = _iJobfilter.GetJobMaster(tag, type);
            return View();
        }
    }
}

TechJobhunt/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TechJobhunt.Models;
namespace TechJobhunt.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Route("/aboutus")]
        public IActionResult AboutUs()
        {
            return View();
        }
        [Route("/contactus")]
        public IActionResult ContactUs()
        {
            return View();
        }
        [Route("/privacy-policy")]
        public IActionResult Privacy()
        {
            return View();
        }
        [Route("/corporatememe")]
        public IActionResult CorporateMeme()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TechJobhunt/Areas/BatchJob/Views/JobListener/TechPanel.cshtml
@{
    ViewData["Title"] = "TechPanel";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@if (ViewBag.Description != null)
{
    @Html.Raw(ViewBag.Description)
}

TechJobhunt/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AppName</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AppName</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

TechJobhunt/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "AboutUs";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<div class="about-container">
    <h2>About Us</h2>
    <p>Welcome to TechJobHunt, your ultimate hub for career growth and business success. We are dedicated to connecting passionate job seekers with dynamic employers across various industries. Our platform is designed to cater to both technical and non-technical fields, ensuring a comprehensive approach to career development and recruitment.</p>
    <div class="aboutus-content">
       <ul>
           <li>
        <h3>Our Mission</h3>
                <p>At TechJobhunt, our mission is to empower individuals and organizations by bridging the gap between talent and opportunity. We strive to be the premier destination for job seekers looking to find their dream jobs and for employers seeking exceptional talent to fuel their growth.</p>
        </li>
        <li>
                <h3>What We Offer</h3>
                <p><strong>Extensive Job Listings:</strong> We feature an extensive array of job listings that span across multiple industries and disciplines. Whether you are a software engineer, a project manager, a creative designer, or a customer service representative, our platform hosts opportunities that align with your career goals.</p>
                <p><strong>In-Depth Documentation: </strong>Navigating the job market and the hiring process can be daunting. Our comprehensive documentation section is here to simplify this journey. From crafting the perfect resume and preparing for interviews to understanding the nuances of job contracts and onboarding, we provide step-by-step guides and practical advice.</p>
                <p><strong>Insightful Blog Content:</strong> Stay ahead of the curve with our blog, which is rich with content tailored to both technical and non-technical audiences. We cover a wide range of topics including industry trends, career development tips, technological advancements, and personal growth stories. Our blog is designed to educate, inspire, and motivate our readers.</p>
         </li>
         <li>
                <h3>Our Values</h3>
                <p><strong>Inclusivity:</strong> We believe in fostering an inclusive environment that embraces diversity and promotes equal opportunities for all. Our platform is designed to support professionals from varied backgrounds, ensuring that everyone has access to opportunities that suit their skills and aspirations.</p>
                <p><strong>Quality:</strong> We are committed to delivering excellence in every aspect of our platform. From the jobs we post to the resources we provide, quality is our hallmark. We carefully curate our content and listings to ensure they meet the highest standards.></p>
                <p>
                    <strong>Innovation:</strong> In a constantly evolving job market, we stay ahead by integrating the latest technologies and trends into our platform. Our innovative approach ensures that both job seekers and employers have access to cutting-edge tools and resources.
                </p>
            </li>
        <li>
                <h3>Join Us</h3>
                <p>
                    Whether you're on a quest to advance your career or looking to build a formidable team, TechJobhunt is your partner in success. Explore our extensive job listings, dive into our detailed documentation, and get inspired by our insightful blog. Together, we can achieve new heights.
                </p>
        </li>
        </ul>
    </div>
</div>

TechJobhunt/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="about-container conatct-containers">
    
   
		<div class="container contact-form-cls">
			<div class="row">
				<h1>contact us</h1>
			</div>
			<div class="row">
				<h4 style="text-align:center">We'd love to hear from you!</h4>
			</div>
			<div class="row input-container">
				<div class="col-xs-12">
					<div class="styled-input wide">
					
						<input type="text" required placeholder="Full Name..." />
						
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
					<div class="styled-input">
						<input type="text" required placeholder="Email..."/>
						
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
					<div class="styled-input" style="float:right;">
						<input type="text" required Phone Number... />
						
					</div>
				</div>
				<div class="col-xs-12">
					<div class="styled-input wide">
						<textarea required placeholder="Message..."></textarea>
						
					</div>
				</div>
				<div class="col-xs-12">
					<div class="btn-lrg submit-btn enquiry-sbm-btn">Send Message</div>
				</div>
			</div>  
</div>

</div>

TechJobhunt/Views/Home/CorporateMeme.cshtml
@{
    ViewData["Title"] = "CorporateMeme";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h1>CorporateMeme</h1>

TechJobhunt/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Find Your Dream Tech Job</h1>
<div class="search-box">
<p>Search for exciting opportunities in the tech industry.</p>
    <form action="#">
        <div class="job-search-cls">
            <i class="fas fa-search"></i>
            <input type="text" id="job-title" name="job-title" placeholder="e.g. Software Engineer">
            <div id="job-title-suggestions" class="autocomplete-suggestions"></div>
        </div>
        <div class="job-search-cls">
            <i class="fas fa-map-marker-alt"></i>
            <input type="text" id="location" name="location" placeholder="e.g. New York, NY">
            <div id="location-suggestions" class="autocomplete-suggestions"></div>
        </div>
        <button type="submit" class="job-sbm-btn">Search Jobs</button>
    </form>
</div>

TechJobhunt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-IN">
<head>
    <meta charSet="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Technical Career</title>
    <meta name="author" content="techjobhunt" />
    <meta property="og:url" content="https://techjobhunt.com/" />
    <meta property="og:site_name" content="TechJobHunt" />
    <meta property="og:title" content="Technical Career" />
    <meta property="og:description" content="Discover technical job and support" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="https://img1.wsimg.com/isteam/stock/unaQxdNZD8SPyDV8E" />
    <meta property="og:locale" content="en_IN" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
</head>
<body>
    <header>
        <a href="/">
            <img src="/images/tech_logo1.png" alt="Tech Jobs Logo">
        </a>
        <nav>
            <ul>
                <li><a href="/">Tech Career</a></li>
                <li><a href="/aboutus">About Us</a></li>
                <li><a href="/contactus">Contact Us</a></li>
                <li><a href="/privacy-policy">Privacy Policy</a></li>
                <li><a href="corporatememe">Corporate Meme</a></li>

                <li class="auth">
                    <a href="#" data-bs-toggle="modal" data-bs-target="#login-modal-popup" class="btn btn-primary login-register-cls">Login/Register <i class="fas fa-sign-in-alt"></i></a>
                    
                </li>
            </ul>
        </nav>
    </header>
    <main class="hero">
        @RenderBody()
    </main>
    <section class="why-choose-us">
        <div class="choose-us-head">
            <h2>Why Choose Us? <div class="face-think-icon"><i class="fa-solid fa-face-thinking"></i></div></h2>
        </div>
        <div class="why-choose-para">
        <ul>
                <li><div class="li-item-box"><strong>Wide range of tech job postings&nbsp; <i class="fa-regular fa-briefcase"></i></strong> Access a diverse array of job listings across various tech fields, ensuring that you find the perfect fit for your skills and career goals.</div></li>
                <li><div class="li-item-box"><strong>Easy-to-use search filters&nbsp; <i class="fa-solid fa-filter"></i></strong> Utilize intuitive search filters to narrow down your job hunt by location, job type, experience level, and more.</div></li>
                <li><div class="li-item-box"><strong>Connect directly with employers &nbsp;<i class="fa-solid fa-phone"></i></strong> Establish direct communication with potential employers, increasing your chances of landing your dream job.</div></li>
                <li><div class="li-item-box"><strong>Career advice and resources &nbsp;<i class="fa-solid fa-graduation-cap"></i></strong> Benefit from expert career advice and resources to help you navigate your job search and career development.</div></li>
        </ul>
        </div>
    </section>
    @await Html.PartialAsync("_LoginPartial")
    <section class="browse-section">
        <h1>Browse Jobs & Companies</h1>
        <div class="browse-filters">
            <button onclick="showCategory('job-lists')">Job Title</button>
            <button onclick="showCategory('category-ai')">Data, AI & ML</button>
            <button onclick="showCategory('category-skills')">Skills</button>
            <button onclick="showCategory('category-popular-Searches')">Popular Searches</button>
            <button onclick="showCategory('category-DomainCatagory')">Category</button>
            <button onclick="showCategory('category-TopComnay')">Top Companies</button>
        </div>
        <div class="job-lists catagory-list-data active" id="job-lists">
            <div class="job-column">
                <a asp-action="TechPanel" asp-controller="JobListener" asp-area="BatchJob" asp-route-tag="Jobtype" asp-route-type="ASP.NET" target="_blank">.NET Developer</a>
                <a asp-action="TechPanel" asp-controller="JobListener" asp-area="BatchJob" asp-route-tag="Jobtype" asp-route-type="BussAst" target="_blank">Business Analyst</a>
                <a href="#">Cyber Security Analyst</a>
                <a href="#">Data Scientist</a>
                <a href="#">DevOps Engineer</a>
                <a asp-action="TechPanel" asp-controller="JobListener" asp-area="BatchJob" asp-route-tag="Jobtype" asp-route-type="Fullstackdev" target="_blank">Full Stack Developer</a>
                <a href="#">Game Developer</a>
            </div>
            <div class="job-column">
                <a href="#">IT help desk</a>
                <a href="#">IT Support</a>
                <a href="#">Network Administrator</a>
                <a href="#">Network Engineer</a>
                <a href="#">Product Manager</a>
                <a href="#">Program Manager</a>
                <a href="#">Project Management</a>
            </div>
            <div class="job-column">
                <a href="#">Project Manager</a>
                <a href="#">QA Tester</a>
                <a href="#">Quality Analyst</a>
                <a href="#">Salesforce Developer</a>
                <a href="#">Scrum Master</a>
                <a href="#">SDET</a>
                <a href="#">SEO jobs</a>
            </div>
            <div class="job-column">
                <a href="#">SOC Analyst</a>
                <a href="#">Software Developer</a>
                <a href="#">Software Engineer</a>
                <a href="#">Solution Architect</a>
                <a href="#">Systems Administrator</a>
                <a href="#">Tech Sales</a>
                <a href="#">Web Developer</a>
            </div>
        </div>
        <div class="category-ai catagory-list-data" id="category-ai">
            <div class="job-column">
                <a href="#">Artificial Intelligence</a>
                <a href="#">Embedded System</a>
            </div>
            <div class="job-column">
                <a href="#">Machine Learning</a>
                <a href="#">Chatgpt</a>
            </div>
            <div class="job-column">
                <a href="#">Data Science</a>
            </div>
            <div class="job-column">
                <a href="#">IOT</a>
            </div>
        </div>
        <div class="category-skills catagory-list-data" id="category-skills">
            <div class="job-column">
                <a href="#">C#</a>
                <a href="#">.NET Framework</a>
                <a href="#">.NET Core</a>
                <a href="#">Entity Framework</a>
            </div>
            <div class="job-column">
                <a href="#">C</a>
                <a href="#">C++</a>
                <a href="#">OOps</a>
            </div>
            <div class="job-column">
                <a href="#">Java</a>
                <a href="#">Spring Framework</a>
                <a href="#">Advanced Java</a>
            </div>
            <div class="job-column">
                <a href="#">React JS</a>
                <a href="#">Angular JS</a>
                <a href="#">TypeScript</a>
            </div>
        </div>
        <div class="category-popular-Searches catagory-list-data" id="ategory-popular-Searches">
            <div class="job-column">
                <a href="#">Master Data Structure</a>
                <a href="#">Full Stack Development</a>
                <a href="#">Use Chatgpt</a>
                <a href="#">SDLC Model</a>
            </div>
            <div class="job-column">
                <a href="#">Github Use</a>
                <a href="#">Git Control System</a>
                <a href="#">React Framework</a>
            </div>
            <div class="job-column">
                <a href="#">Software Engineering</a>
                <a href="#">AI World</a>
                <a href="#">Advanced Java</a>
            </div>
            <div class="job-column">
                <a href="#">React JS</a>
                <a href="#">Angular JS</a>
                <a href="#">TypeScript</a>
            </div>
        </div>
        <div class="category-DomainCatagory catagory-list-data" id="category-DomainCatagory">
            <div class="job-column">
                <a href="#">Software Engineering</a>
                <a href="#">BioTech Engineering</a>
                <a href="#">Support Engineer </a>
                <a href="#">Network Engineer</a>
            </div>
            <div class="job-column">
                <a href="#">Mechanical Engineering</a>
                <a href="#">Civil Engineering</a>
                <a href="#">Electrical/Electronics</a>
            </div>
            <div class="job-column">
                <a href="#">Risk Analyst</a>
                <a href="#">CA</a>
                <a href="#">Bussiness Analyst</a>
            </div>
            <div class="job-column">
                <a href="#">Public Administration</a>
                <a href="#">Finanace Management</a>
                <a href="#">HR Management</a>
            </div>
        </div>
        <div class="category-TopComnay catagory-list-data" id="category-TopComnay">
            <div class="job-column">
                <a href="#">Google</a>
                <a href="#">Facebook</a>
                <a href="#">Atlassian </a>
                <a href="#">Wipro</a>
            </div>
            <div class="job-column">
                <a href="#">Microsoft</a>
                <a href="#">HCL</a>
                <a href="#">TCS</a>
            </div>
            <div class="job-column">
                <a href="#">Apple</a>
                <a href="#">Meta</a>
                <a href="#">Swiggy</a>
            </div>
            <div class="job-column">
                <a href="#">Zomato</a>
                <a href="#">Netflix</a>
                <a href="#">JioCinema</a>
            </div>
        </div>
    </section>
    <footer>
        <p>Copyright &copy; 2024-2025 TechJobhunt. All Rights Reserved.</p>
    </footer>
</body>
</html>

TechJobhunt/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en-IN">
<head>
    <meta charSet="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Technical Career</title>
    <meta name="author" content="techjobhunt" />
    <meta property="og:url" content="https://techjobhunt.com/" />
    <meta property="og:site_name" content="TechJobHunt" />
    <meta property="og:title" content="Technical Career" />
    <meta property="og:description" content="Discover technical job and support" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="https://img1.wsimg.com/isteam/stock/unaQxdNZD8SPyDV8E" />
    <meta property="og:locale" content="en_IN" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/main.js"></script>
</head>
<body>
    <header>
        <a href="/">
            <img src="/images/tech_logo1.png" alt="Tech Jobs Logo">
        </a>
        <nav>
            <ul>
                <li><a href="/">Tech Career</a></li>
                <li><a href="/aboutus">About Us</a></li>
                <li><a href="/contactus">Contact Us</a></li>
                <li><a href="/privacy-policy">Privacy Policy</a></li>
                <li><a href="/corporatememe">Corporate Meme</a></li>

                <li class="auth">
                    <a href="#" data-bs-toggle="modal" data-bs-target="#login-modal-popup" class="btn btn-primary login-register-cls">Login/Register <i class="fas fa-sign-in-alt"></i></a>

                </li>
            </ul>
        </nav>
    </header>
    <main class="hero-section-cls">
        @RenderBody()
    </main>
    <section class="why-choose-us">
        <div class="choose-us-head">
            <h2>Why Choose Us? <div class="face-think-icon"><i class="fa-solid fa-face-thinking"></i></div></h2>
        </div>
        <div class="why-choose-para">
            <ul>
                <li><div class="li-item-box"><strong>Wide range of tech job postings&nbsp; <i class="fa-regular fa-briefcase"></i></strong> Access a diverse array of job listings across various tech fields, ensuring that you find the perfect fit for your skills and career goals.</div></li>
                <li><div class="li-item-box"><strong>Easy-to-use search filters&nbsp; <i class="fa-solid fa-filter"></i></strong> Utilize intuitive search filters to narrow down your job hunt by location, job type, experience level, and more.</div></li>
                <li><div class="li-item-box"><strong>Connect directly with employers &nbsp;<i class="fa-solid fa-phone"></i></strong> Establish direct communication with potential employers, increasing your chances of landing your dream job.</div></li>
                <li><div class="li-item-box"><strong>Career advice and resources &nbsp;<i class="fa-solid fa-graduation-cap"></i></strong> Benefit from expert career advice and resources to help you navigate your job search and career development.</div></li>
            </ul>
        </div>
    </section>
    @await Html.PartialAsync("_LoginPartial")
    <section class="browse-section">
        <h1>Browse Jobs & Companies</h1>
        <div class="browse-filters">
            <button>Job Title</button>
            <button>Data, AI & ML</button>
            <button>Skills</button>
            <button>Popular Searches</button>
            <button>Category</button>
            <button>Top Companies</button>
        </div>
        <div class="job-lists">
            <div class="job-column">
                <a >.NET Developer</a>
                <a href="#">Business Analyst</a>
                <a href="#">Cyber Security Analyst</a>
                <a href="#">Data Scientist</a>
                <a href="#">DevOps Engineer</a>
                <a href="#">Full Stack Developer</a>
                <a href="#">Game Developer</a>
            </div>
            <div class="job-column">
                <a href="#">IT help desk</a>
                <a href="#">IT Support</a>
                <a href="#">Network Administrator</a>
                <a href="#">Network Engineer</a>
                <a href="#">Product Manager</a>
                <a href="#">Program Manager</a>
                <a href="#">Project Management</a>
            </div>
            <div class="job-column">
                <a href="#">Project Manager</a>
                <a href="#">QA Tester</a>
                <a href="#">Quality Analyst</a>
                <a href="#">Salesforce Developer</a>
                <a href="#">Scrum Master</a>
                <a href="#">SDET</a>
                <a href="#">SEO jobs</a>
            </div>
            <div class="job-column">
                <a href="#">SOC Analyst</a>
                <a href="#">Software Developer</a>
                <a href="#">Software Engineer</a>
                <a href="#">Solution Architect</a>
                <a href="#">Systems Administrator</a>
                <a href="#">Tech Sales</a>
                <a href="#">Web Developer</a>
            </div>
        </div>
    </section>
    <footer>
        <p>Copyright &copy; 2024-2025 TechJobhunt. All Rights Reserved.</p>
    </footer>
</body>
</html>